### ISSUE TITLE
USER STORY: Ability to leave comments on posts

### ISSUE THREAD

**Issue by Libbu** [Libbu/Full-Craic#10]
As a student I can leave comments on the site to engage with site-owners.

### Acceptance Criteria:
- Acceptance Criteria 1: comment form present on side
* Acceptance Criteria 2: users must be logged in to comment
+ Acceptance Criteria 3: comments can be submitted.

### Tasks
- [ ] Task 1: comment model in db with relevant connections
- [ ] Task 2: url views
- [ ] Task 3: comment form exists
